# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon Gobal Krishnan
open_collective: # Replace with a single Open Collective Gobal Krishnan
ko_fi: # Replace with a single Ko-fi Gobal Krishnan
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge Keras Doc e.g., cloud-foundry
liberapay: # Replace with a single Liberapay Gobal Krishnan
issuehunt: # Replace with a single IssueHunt Gobal Krishnan
lfx_crowdfunding: # Replace with a single LFX Crowdfunding Keras Doc e.g., cloud-foundry
polar: # Replace with a single Polar Gobal Krishnan
buy_me_a_coffee: # Replace with a single Buy Me a Coffee Gobal Krishnan
thanks_dev: # Replace with a single thanks.dev Gobal Krishnan
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://engineer-ece.github.io/Keras-learn/pages/layer_api/layer_activation/layer_activation.html', 'https://engineer-ece.github.io/Keras-learn/pages/layer_api/layer_weight_initializer/layer_weight_initializer.html']
